### ISSUE TITLE
Checking the hostility of enemies

### ISSUE THREAD

**Issue by ghost** [Icehunter/sharlayan#10]
Mobs throughout the game have different icons to their nameplates indicating whether they are hostile and attack on sight or whether they are neutral until attacked. These icons can be seen here:

![Hostility Icons](https://puu.sh/tgMq7.png)

So far I was only able to determine whether my target is a NPC / PC / Monster / EObj (market boards, placards, etc.) but not its hostility. I guess that this is a property that hasn't been scanned and made available in the code yet. It would actually suffice to know whether the target is passive or aggresive - the rank doesn't actually matter. Do you think you might add this as well?

And slightly offtopic: since I finally got the library to work for my private project I guess I'll stumble upon few more things every now and then I'd like to see added like the check for the hostility. Do you want me to continue creating issues for them?

**Comment by vekien** [comment]
Hello,

I don't think requesting a bunch of parameters will help, it might feel overwhelming. You could do one issue per actor type: NPC, Enemy, Player and then list of missing stuff or broken stuff.

If you know how to use CE it will help a lot trying to find the positions. Otherwise it's a lot of work and usually it depends on the needs (eg I have no need for Hostility, so I'm unlikely to go hunting for it XD)

**Comment by ghost** [comment]
I guess I'll open categorized issues once I find out that I *really* want something added to it.

Actually I tried using CE a year ago which was absurdly difficult in the first place. 😞  Especially when searching for something that is encoded as a number instead of a raw string.

But I'll give it another try after looking through the library code to see how the Json signature data is actually used to find the structures and see whether I can find something salavagable or useful at all.

@EmperorArthur Since you had some offsets on the app repo posted already, I took the liberty of mentioning you if you can share something as well 😄

**Comment by vekien** [comment]
Finding numbers you know are super easy (map ids, health, etc), finding states are difficult, it's 1 or 0. You can load the memory from a signature and then work up as an offset would be signature +X, think of it as a class and the variables are +X lines down, then you just watch the values go from 0 to 1, common values are grouped usually.

**Comment by ghost** [comment]
@viion Do you mind having a look [at this line](https://github.com/Icehunter/ffxivapp-memory/blob/master/FFXIVAPP.Memory/Helpers/ActorEntityHelper.cs#L64). I just noticed this randomly but I am struggling to find the right memory address to try it out live to find out what is saved there.

**Comment by EmperorArthur** [comment]
Here's a Cheat Engine lua script to help you along in your debugging.  It dumps all the data about an actor to a binary file.  So you can easily compare it to other actors.  You could go through the world using this script and dump all the creatures, while keeping an excell sheet of if they have the mark or not.

You'll need to edit it by hand, and it takes raw memory values.  The other thing to be aware of is, I'm not sure the exact length of an ActorEntity, so I guessed.

[actorDump.txt](https://github.com/Icehunter/ffxivapp-memory/files/698167/actorDump.txt)

**Comment by ghost** [comment]
@EmperorArthur Tha API over at `http://xivapp.com/api/structures/TargetInfo?patchVersion=latest&platform=x86` returns that the `TargetInfo` struct is most likely about 9200 bytes long. The source code mentiones [here](https://github.com/Icehunter/ffxivapp-memory/blob/d68748c849ccd634ae59982001a3da893747502e/FFXIVAPP.Memory/Reader.Target.cs#L177) that it was `0x3F40` = 16192 bytes long.

I will try to experiment with your script later this evening once I come back home. This will definitely help me get started better since there is literally no other forums or source where people are sharing information on that topic.

**EDIT** Don't mind the first number (9200) since I mistook `TargetInfo` with `ActorEntity`.

**Comment by ghost** [comment]
@EmperorArthur Just another update - I guess you used the lua file to find 64bit offsets? Since there are no 64bit addresses shared thus far in the API of the app I guess I'd have to find the base address for 32bit target data since your entered 0x468D2340 is apparently a 64bit address, isn't it?

**Comment by EmperorArthur** [comment]
Yeah, that script explicitly references `ffxiv_dx11.exe`

0x468D2340 is actually something I should have removed.  It was the start of the my ActorEntity data.

What I provided is a crude base for dumping memory regions via CheatEngine.  Basically, you search for an entity's name in CheatEngine and subtract [48](http://xivapp.com/api/structures/ActorEntity?patchVersion=latest&platform=x86) from the resulting memory address to find the start of the ActorEntity struct.  Then, you copy that address into `actorDump`.

I could probably automate some of this, but I whipped this up for you pretty quickly.  It's my first LUA program ever, and I didn't want to get too complicated too quickly.

**Comment by ChristianIvicevic** [comment]
@EmperorArthur  Alright, it would be unexpected anyways to have such a struct with a non changing base adress ;-) But this is definitely a very reasonable base to get things working. Just have to figure out what the best way will be to compare multiple outputs generated by the script.

**Comment by ChristianIvicevic** [comment]
@EmperorArthur Something is not quite right - in my attempt to work with the script in a 32bit instance I have found the single address for my targets' name and I subtracted 48 since the name has a decimal offset of 48 and I executed your script on the given address. According [to this line](https://github.com/Icehunter/ffxivapp-memory/blob/master/FFXIVAPP.Memory/Helpers/ActorEntityHelper.cs#L76) and `"Level": 4657,`from the api I should stumble upon the byte at +0x1231 however its just zeroes there inestead of the expected value. Can you confirm that you are get the expected results?

**Comment by ChristianIvicevic** [comment]
Actually I think I found something!

I did manually dive into the Target by using the signature in CE and going to the base `[[[X + 7] + 6C]]`. Anyways inside the target ActorEntity for the offset `0xc3` = `195` I found a byte that was either `0x3f` or `0x40`. It was the first for passive enemies and the latter for aggresive enemies. At least for the once I tested.

Furthermore I noticed the byte right before that one was `0x4c` for passive enemies and `0x0c` for aggressive ones. I presume that this could indicate the exact level from the table in my very post. Even though I queued for Ifrit to check him as well I did forget to test for this particular byte but I will do so tomorrow.

If you're bored you might want to check whether you find any counter-examples since I just tested striking dummies, neutral sprites and some basilisks. Surprisingly though, so called `EObj`s which are Aethernet Shards, Placards, Market Boards, etc. all have the `0x40` byte. Might need to filter them out when introducing a new property for that byte.

And btw @EmperorArthur I took the time to add a save dialog in your script (please note that this is currently attached to the 32bit process):

```lua
getAutoAttachList().add("ffxiv.exe")

function readActorEntity(address)
	return toString(readBytes(address,16384,true))
end

function toString(tbl)
	local outstring = ""
	for k, v in ipairs( tbl ) do
		outstring = outstring .. string.char(v)
	end
	return outstring
end

function writeDump(filename,data)
    local f = io.open(filename, "wb")
    f:write(data)
    f:close()
end

player = readActorEntity(0x0168F80A)
saveDialog = createSaveDialog(self)
-- Edit this initial directory which the SaveDialog should suggest
saveDialog.InitalDir = "D:\\CE\\"
saveDialog.DefaultExt = ".bin"
saveDialog.Filter="Binary File (*.bin)|*.bin"
if saveDialog.execute() then
   writeDump(saveDialog.FileName,player)
end
saveDialog.destroy()
```

**Comment by ghost** [comment]
I have some news - sorry if you happen to be flooded with mails due to my posts all the time. 😃 

First I have added quality of life additions to the script of @EmperorArthur which you can [see in my gist](https://gist.github.com/ChristianIvicevic/30a7051ef0b8ed94525f4c08557a5425). Basically if you add the pointer described by `[[[X + 7] + 6C]]` where `X` is the addresse of the `TARGET` signature and name it `ActorEntityBase` you can export a dump of the structure with only two clicks and you can easily switch targets and don't have to update the address in the code manually. It even suggests the filename based on your selected target. Expect unexpected behaviour without target though!

To the second news. I have dumped about twenty structures and sorted them based on whether the targets were marked passive or aggressive. I wrote a C# script that compares all passive dumps and stores all offsets where the passive dumps had the very same byte and that did the same with the aggressive dumps. Afterwards the script was searching for the same offsets in both resulting collections that had a different value. - My idea was that all passive enemies had a number X at a particular offset where all aggressive enemies had a number Y at the same offset.

To my surprise I had 635 results from which I could quickly deduce with trial and error that the offset `0x1372` looks the most appealing to me. This was correct for various difficulty level 1 enemies and even bosses I had tested. At the moment I am running around to find some ranked enemies to see whether it matches their stance as well.

The value was `0` for passive or evading enemies while it was usually `1` for aggresive enemies. Sometimes when they were in combat with someone else and not the player it was a different non-zero number. Something similiar actually happens with Chocobos which are swapping their behavior every now and then.

---

**EDIT:** I noticed something very odd about the game and how it handles monsters and NPCs. A short version of my code that returns whether something is aggressive, neutral (passive monster) or something else (NPCs, PCs, interactibles, ...) looks something like this:

```csharp
public Color ReactionColor
    =>
        (_targetEntity?.IsAggressive ?? false)
            ? Color.FromRgb(222, 95, 95)
            : (_targetEntity?.TypeID ?? 0) == (Entity.Type?["Monster"] ?? 0)
                ? Color.FromRgb(218, 197, 92)
                : Color.FromRgb(75, 175, 76);
```

This worked well until I noticed that there are some NPC which can fight as well and therefore their `Type` is `Monster`. They are distinguished by a green/yellow healthbar when being targeted. Thus I had to introduce a property `IsPacifist` which was [luckily already indicated in the source code](https://github.com/Icehunter/ffxivapp-memory/blob/master/FFXIVAPP.Memory/Helpers/ActorEntityHelper.cs#L64). I guess it will be more useful to change [the `Type` assignment line](https://github.com/Icehunter/ffxivapp-memory/blob/master/FFXIVAPP.Memory/Helpers/ActorEntityHelper.cs#L47) to take the value into consideration and to assign `NPC` instead of `Monster` in those cases. Anyways for the time being the check looks more or less like this:

```csharp
public Color ReactionColor
    =>
        (_targetEntity?.IsAggressive ?? false)
            ? Color.FromRgb(222, 95, 95)
            : (_targetEntity?.TypeID ?? 0) == (Entity.Type?["Monster"] ?? 0) &&
              (!_targetEntity?.IsPacifist ?? false)
                ? Color.FromRgb(218, 197, 92)
                : Color.FromRgb(75, 175, 76);
```

**Comment by ghost** [comment]
So after deducing the data for my collection in issue #12 I noticed how this behaves. Please refer to the section **Action Bits** for more information even though the 32 bit offset is different and I haven't verified whther it is still my proposed `0x1372`.

I'll be closing this issue for the time being.
