### ISSUE TITLE
PlayerEntity memory incorrect?

### ISSUE THREAD

**Issue by logicallysynced** [Icehunter/sharlayan#21]
Sorry for all the bug reports/questions..

I've noticed I can't get a read on the PlayerEntity model. I'm trying to access the "Name" variable but also the other variables in the model seem to be incorrect also.

    var name = Reader.GetPlayerInfo().PlayerEntity.Name;
    //returns random string data.

Are the memory offsets incorrect or is this model depreciated now? I'm trying to use it to compare against the ConcurrentDictionary of ActorEntity to find the active player on the game.

**Comment by Icehunter** [comment]
Debugging through shows correct on my end. Have you setup log4view to view logs from the app in real time?

**Comment by logicallysynced** [comment]
Yeah for some reason I'm struggling to get the same results (DX11)

    var PlayerInfo = Reader.GetActors()?.PCEntities?.FirstOrDefault().Value;
                    
                    var MyselfInfo = Reader.GetPlayerInfo()?.PlayerEntity;
                    var PlayerInfo = Reader.GetActors()?.PCEntities?.FirstOrDefault().Value;

                    Debug.WriteLine("Name: " + MyselfInfo.Name + "//" + PlayerInfo.Name);
                    Debug.WriteLine("Dex: " + MyselfInfo.BaseDexterity);

It outputs:
  
![capture](https://user-images.githubusercontent.com/11515784/27775929-bc03dcf8-5fe5-11e7-8c97-c7a105f3f7c7.PNG)


So PlayerInfo is correct reading from the Actors, its PlayerEntity which seems to be weird.

**Comment by Icehunter** [comment]
I'll have a look at the offset; also have you joined our discord channel? :)

**Comment by logicallysynced** [comment]
Just joined the Discord ^^

**Comment by Icehunter** [comment]
Fixed :)
