### ISSUE TITLE
How to get player position?

### ISSUE THREAD

**Issue by vekien** [Icehunter/sharlayan#36]
Back when this was memory module I could get the current players position via:

```csharp
ActorReadResult readResult = Reader.GetActors();
ActorEntity player = readResult.PCEntities.First().Value;

player.X
player.Y
player.MapId
// etc
```

But `First()` is no longer "you", it can be any random person. My assumption is that this is because the memory now deletes all previously recorded entities, so whenever you call `readResult` it's already deleted some... Maybe...

Since `PlayerInfo` doesn't provde anything, what is best way to get the position of your own character?

**Comment by Icehunter** [comment]
https://github.com/Icehunter/sharlayan/blob/master/Sharlayan/Core/ActorEntity.cs#L113

```csharp
var player = ActorEntity.CurrentUser;
```

Just reference the static after you've read.
