### ISSUE TITLE
A couple things broken with 6.1 patch

### ISSUE THREAD

**Issue by SolenoidMan** [Icehunter/sharlayan#66]
Patch 6.1 changed a few addresses im guessing regarding CurrentPlayerInfo, though Inventory and Chat retrieval appear unaffected.
A few player properties now return null. HP, GP, Heading, MapZone, etc.

**Comment by Icehunter** [comment]
@SolenoidMan can you check after latest resources update. Is this fixed for you?

**Comment by SolenoidMan** [comment]
Yes! It was the zones-latest.json, etc. files, I deleted them and then everything worked again on regeneration. Thankyou!
